Repository wintercms/winter, pull requests merged in 2021-07, with the labels that each got.

#222 Return 404 for asset combiner resources that don't exist
  modules/system/classes/CombineAssets.php
  modules/system/classes/SystemController.php
Labels: Status: Revision Needed, Type: Maintenance

#226 Fix plugin status update issue
  modules/system/classes/PluginManager.php
Labels: Status: Completed, Type: Maintenance

#245 Add client-side localization strings for german locale
  modules/system/lang/de/client.php
Labels: Status: Accepted, Type: Maintenance

#246 add compiled client language files
  modules/system/assets/js/lang/lang.de.js
  modules/system/assets/js/lang/lang.ro.js
Labels: Type: Maintenance

#235 Add trusted proxy configuration variables
  config/app.php
Labels: Status: Completed, Type: Enhancement
