Repository wintercms/winter, pull requests merged in 2021-03, with the labels that each got.

#34 Support arbitrary depth of dependsOn fields
  modules/backend/widgets/form/assets/js/winter.form.js
Labels: Status: Completed, Type: Maintenance

#36 Add October\Rain namespace in validateModel for compatibility
  modules/backend/behaviors/ReorderController.php
Labels: Status: Completed, Type: Maintenance

#38 Rebrand winter:install
  modules/system/console/WinterInstall.php
Labels: Status: Completed, Type: Maintenance

#43 Fixed tooltip in first column of Lists widget not working
  modules/system/assets/ui/js/list.rowlink.js
  modules/system/assets/ui/storm-min.js
Labels: Status: Completed, Type: Maintenance

#49 Unbind event handlers upon destruction of the form widget
  modules/backend/widgets/form/assets/js/winter.form.js
  modules/system/assets/ui/js/popup.js
  modules/system/assets/ui/storm-min.js
Labels: Status: Review Needed, Type: Maintenance

#54 Update footer copyright in demo theme
  themes/demo/partials/site/footer.htm
Labels: Status: Completed, Type: Maintenance

#47 Add support for pivot data in deferred bindings
  .github/workflows/tests.yml
  modules/system/database/migrations/2021_10_01_000025_Db_Add_Pivot_Data_To_Deferred_Bindings.php
  tests/fixtures/plugins/database/tester/models/Author.php
  tests/fixtures/plugins/database/tester/models/Category.php
  tests/fixtures/plugins/database/tester/models/Post.php
  tests/fixtures/plugins/database/tester/models/Tag.php
  tests/fixtures/plugins/database/tester/updates/create_posts_table.php
  tests/fixtures/plugins/database/tester/updates/create_tags_table.php
  tests/fixtures/plugins/database/tester/updates/version.yaml
  tests/unit/plugins/database/BelongsToManyModelTest.php
  tests/unit/plugins/database/MorphManyModelTest.php
Labels: Type: Maintenance

#55 Change password reset messaging to remove user not found
  modules/backend/controllers/Auth.php
  modules/backend/lang/be/lang.php
  modules/backend/lang/bg/lang.php
  modules/backend/lang/ca/lang.php
  modules/backend/lang/cs/lang.php
  modules/backend/lang/da/lang.php
  modules/backend/lang/de/lang.php
  modules/backend/lang/el/lang.php
  modules/backend/lang/en/lang.php
  modules/backend/lang/es-ar/lang.php
  modules/backend/lang/es/lang.php
  modules/backend/lang/et/lang.php
  modules/backend/lang/fa/lang.php
  modules/backend/lang/fi/lang.php
  modules/backend/lang/fr/lang.php
  modules/backend/lang/hu/lang.php
  modules/backend/lang/id/lang.php
  modules/backend/lang/it/lang.php
  modules/backend/lang/ja/lang.php
  modules/backend/lang/kr/lang.php
  modules/backend/lang/lt/lang.php
  modules/backend/lang/lv/lang.php
  modules/backend/lang/nb-no/lang.php
  modules/backend/lang/nl/lang.php
  modules/backend/lang/pl/lang.php
  modules/backend/lang/pt-br/lang.php
  modules/backend/lang/pt-pt/lang.php
  modules/backend/lang/ro/lang.php
  modules/backend/lang/rs/lang.php
  modules/backend/lang/ru/lang.php
  modules/backend/lang/sk/lang.php
  modules/backend/lang/sl/lang.php
  modules/backend/lang/sv/lang.php
  modules/backend/lang/th/lang.php
  modules/backend/lang/tr/lang.php
  modules/backend/lang/uk/lang.php
  modules/backend/lang/vn/lang.php
  modules/backend/lang/zh-cn/lang.php
  modules/backend/lang/zh-tw/lang.php
Labels: Status: Completed, Type: Maintenance

#56 Update lang.php - small corrections
  modules/backend/lang/fr/lang.php
Labels: Status: Completed, Type: Maintenance

#61 Small improvements of the French translation
  modules/backend/lang/fr/lang.php
Labels: Status: Completed, Type: Maintenance

#44 Implement artisan winter:util purge orphans
  modules/system/console/WinterUtil.php
Labels: Status: Completed, Type: Enhancement

#12 [WIP] Add support for selecting locale & timezone in winter:install
  modules/system/console/WinterInstall.php
Labels: Status: Completed, Type: Enhancement

#46 Plugins custom validation rules
  modules/system/ServiceProvider.php
  tests/fixtures/plugins/winter/tester/Plugin.php
  tests/fixtures/plugins/winter/tester/rules/BeLikeBobRule.php
  tests/unit/plugins/system/CustomValidatorRulesTest.php
Labels: Status: Completed, Type: Enhancement

#63 Support specifying step, min, and max attributes on number inputs for list filters
  modules/backend/widgets/Filter.php
  modules/backend/widgets/filter/partials/_scope_number.htm
  modules/backend/widgets/filter/partials/_scope_numberrange.htm
  modules/system/assets/ui/js/filter.dates.js
  modules/system/assets/ui/js/filter.numbers.js
Labels: Status: Testing Needed, Type: Enhancement

#64 Fix errors when we receive html content instead of a mail template name
  modules/system/classes/MailManager.php
Labels: Status: Completed, Type: Maintenance
