Repository wintercms/winter, pull requests merged in 2022-03, with the labels that each got.

#484 Use env() settings by default in config/cms.php
  config/cms.php
Labels: Status: In Progress, Type: Maintenance

#491 Strip double / prefix when uploading to Media root directory
  .vscode/settings.json
  modules/backend/traits/UploadableWidget.php
  modules/system/classes/MediaLibrary.php
Labels: Type: Maintenance, Status: Review Needed

#404 [Enhancement] Refactor winter:env, winter:install to use new EnvFile & ArrayFile parsers
  config/app.php
  config/auth.php
  config/broadcasting.php
  config/cache.php
  config/cms.php
  config/cookie.php
  config/database.php
  config/develop.php
  config/environment.php
  config/filesystems.php
  config/hashing.php
  config/logging.php
  config/mail.php
  config/queue.php
  config/services.php
  config/session.php
  config/view.php
  modules/system/console/WinterEnv.php
  tests/fixtures/config/app.php
  tests/fixtures/config/mail.php
  tests/unit/system/console/WinterEnvTest.php
Labels: Status: Completed, Type: Enhancement

#479 Fix isActive for CMS page with "/" as URL
  modules/cms/classes/Page.php
  tests/unit/cms/classes/PageTest.php
Labels: Status: Completed, Type: Maintenance, Priority: Low

#500 Sync MailSettings model init with L9 mail config changes
  modules/system/models/MailSetting.php
Labels: Type: Maintenance, Status: Review Needed

#495 Multiple file attachments in theme customization
  modules/cms/models/ThemeData.php
Labels: Status: Completed, Type: Maintenance

#502 Prevent error if accessing undefined $resizer variable
  modules/system/classes/SystemController.php
Labels: Status: Completed, Type: Maintenance

#506 Allow disabling/enabling of sorting with Repeater widget
  modules/backend/formwidgets/Repeater.php
  modules/backend/formwidgets/repeater/assets/js/repeater.js
  modules/backend/formwidgets/repeater/partials/_repeater.htm
  modules/backend/formwidgets/repeater/partials/_repeater_item.htm
Labels: Type: Maintenance, Status: Testing Needed

#518 fix null coalescent operator expression
  modules/backend/assets/js/winter-min.js
  modules/backend/formwidgets/codeeditor/assets/js/build-min.js
  modules/backend/formwidgets/richeditor/assets/js/build-plugins-min.js
  modules/backend/widgets/mediamanager/assets/js/mediamanager-browser-min.js
  modules/backend/widgets/table/assets/js/build-min.js
  modules/system/assets/js/framework-min.js
  modules/system/assets/js/framework.combined-min.js
  modules/system/assets/ui/js/filter.js
  modules/system/assets/ui/storm-min.js
Labels: Status: Completed, Type: Maintenance
