Repository wintercms/winter, pull requests merged in 2022-05, with the labels that each got.

#544 Hide smtp user/password fields if smtp authorization is false.
  modules/system/models/MailSetting.php
  modules/system/models/mailsetting/fields.yaml
Labels: Status: Completed, Type: Enhancement

#485 Undefined variable $packagePath
  modules/system/console/MixWatch.php
Labels: Status: Completed, Type: Maintenance

#552 [WIP] 1.2 - AssetMaker respect app.asset_url
  modules/system/traits/AssetMaker.php
Labels: Status: Completed, Type: Maintenance

#178 Force resized images to be regenerated when the source image changes
  modules/system/classes/ImageResizer.php
Labels: Type: Maintenance, Status: Testing Needed

#555 Small refactor to workflow utilities
  .github/workflows/utilities/phpcs-pr
  .github/workflows/utilities/phpcs-push
Labels: Type: Maintenance
