Repository wintercms/winter, pull requests merged in 2022-06, with the labels that each got.

#501 [WIP] Revamp Plugin Manager
  modules/system/classes/PluginBase.php
  modules/system/classes/PluginManager.php
  modules/system/classes/UpdateManager.php
  modules/system/classes/VersionManager.php
  modules/system/console/PluginDisable.php
  modules/system/console/PluginEnable.php
  modules/system/controllers/Updates.php
  modules/system/models/PluginVersion.php
  modules/system/providers.php
  modules/system/reportwidgets/Status.php
  tests/unit/system/classes/PluginManagerTest.php
Labels: Type: Enhancement, Status: In Progress

#580 [FIX] 1.2 Replace plugin eager loading
  modules/system/classes/PluginManager.php
Labels: Status: Completed, Type: Maintenance

#587 Fix site relative partial paths failing in 1.2
  modules/system/console/WinterTest.php
  modules/system/traits/ViewMaker.php
Labels: Type: Maintenance, Status: Revision Needed

#572 Outputs time respecting backend preferences
  modules/cms/controllers/themelogs/_preview_scoreboard.htm
  modules/system/controllers/eventlogs/preview.htm
Labels: Status: Completed, Type: Maintenance

#588 [Fix] 1.2 - PluginManager Normalization
  modules/system/classes/PluginManager.php
  modules/system/tests/classes/PluginManagerTest.php
Labels: Status: Completed, Type: Maintenance

#577 [WIP] MediaManager ImageResizer
  modules/backend/traits/SessionMaker.php
  modules/backend/widgets/MediaManager.php
  modules/backend/widgets/mediamanager/partials/_image-crop-popup-body.php
  modules/system/classes/ImageResizer.php
  modules/system/classes/MediaLibrary.php
Labels: Status: Completed, Type: Maintenance
