Repository wintercms/winter, pull requests merged in 2022-11, with the labels that each got.

#754 [FIX] Required Checkbox
  modules/backend/assets/css/winter.css
  modules/system/assets/ui/less/form.less
  modules/system/assets/ui/storm.css
Labels: Status: Completed, Type: Maintenance

#762 Pass element's maxlength to slugify and toCamel to respect field definition
  modules/system/assets/ui/js/input.preset.js
  modules/system/assets/ui/storm-min.js
Labels: Status: Completed, Type: Maintenance

#765 Prevent previous relations from being unlinked
  modules/backend/behaviors/RelationController.php
Labels: Priority: High, Status: Review Needed

#746 CMS Twig extension `contentFunction()` should return bool like `partialFunction()`
  modules/cms/classes/Controller.php
  modules/cms/tests/classes/TwigExtensionTest.php
  modules/cms/twig/ContentNode.php
  modules/cms/twig/Extension.php
Labels: Status: Completed, Type: Maintenance

#763 Prevent fancy layout styling from spilling over into nested forms
  modules/backend/assets/css/winter.css
  modules/backend/assets/less/layout/fancylayout.less
  modules/backend/models/brandsetting/custom.less
Labels: Status: Completed, Type: Maintenance

#767 Improved Russian translation
  modules/backend/lang/ru/lang.php
  modules/system/lang/ru/validation.php
Labels: Status: Completed, Type: Maintenance

#778 Uncaught ReferenceError: gtag is not defined
  modules/cms/console/scaffold/theme/tailwind/assets/src/js/theme.stub
Labels: Status: Completed, Type: Maintenance

#777 Add AJAX form validation
  modules/system/assets/css/snowboard.extras.css
  modules/system/assets/js/build/system.debug.js
  modules/system/assets/js/build/system.js
  modules/system/assets/js/snowboard/ajax/Request.js
  modules/system/assets/js/snowboard/build/snowboard.extras.js
  modules/system/assets/js/snowboard/build/snowboard.request.js
  modules/system/assets/js/snowboard/extras/FormValidation.js
  modules/system/assets/js/snowboard/snowboard.extras.js
  modules/system/assets/less/snowboard.extras.less
Labels: Status: Completed, Type: Enhancement

#766 Improved Ukrainian translation
  modules/backend/lang/uk/lang.php
  modules/system/lang/uk/validation.php
Labels: Status: Completed, Type: Maintenance

#779 Classloader improvements
  modules/backend/ServiceProvider.php
  modules/cms/ServiceProvider.php
  modules/system/ServiceProvider.php
  modules/system/classes/PluginManager.php
  modules/system/tests/bootstrap/app.php
Labels: Status: Completed, Type: Enhancement
