Repository wintercms/winter, pull requests merged in 2022-04, with the labels that each got.

#486 Scaffolding Improvements
  modules/backend/console/CreateController.php
  modules/backend/console/CreateFormWidget.php
  modules/backend/console/CreateReportWidget.php
  modules/backend/console/scaffold/controller/_list_toolbar.stub
  modules/backend/console/scaffold/controller/config_form.stub
  modules/backend/console/scaffold/controller/config_list.stub
  modules/backend/console/scaffold/controller/controller.stub
  modules/backend/console/scaffold/controller/create.stub
  modules/backend/console/scaffold/controller/index.stub
  modules/backend/console/scaffold/controller/preview.stub
  modules/backend/console/scaffold/controller/update.stub
  modules/cms/console/CreateComponent.php
  modules/cms/console/CreateTheme.php
  modules/cms/console/scaffold/component/component.stub
  modules/system/ServiceProvider.php
  modules/system/console/BaseScaffoldCommand.php
  modules/system/console/CreateCommand.php
  modules/system/console/CreateMigration.php
  modules/system/console/CreateModel.php
  modules/system/console/CreatePlugin.php
  modules/system/console/CreateSettings.php
  modules/system/console/scaffold/command/command.stub
  modules/system/console/scaffold/migration/migration.create.stub
  modules/system/console/scaffold/migration/migration.stub
  modules/system/console/scaffold/migration/migration.update.stub
  modules/system/console/scaffold/model/columns.stub
  modules/system/console/scaffold/model/create_table.stub
  modules/system/console/scaffold/model/fields.stub
  modules/system/console/scaffold/model/model.stub
  modules/system/console/scaffold/plugin/plugin.stub
  modules/system/console/scaffold/plugin/version.stub
  modules/system/console/scaffold/settings/model.stub
  modules/system/console/traits/HasPluginArgument.php
Labels: Status: Completed, Type: Enhancement

#522 Update MailSettings for new Laravel mail config structure.
  config/mail.php
  modules/system/lang/be/lang.php
  modules/system/lang/bg/lang.php
  modules/system/lang/ca/lang.php
  modules/system/lang/cs/lang.php
  modules/system/lang/da/lang.php
  modules/system/lang/de/lang.php
  modules/system/lang/el/lang.php
  modules/system/lang/en/lang.php
  modules/system/lang/es/lang.php
  modules/system/lang/et/lang.php
  modules/system/lang/fa/lang.php
  modules/system/lang/fi/lang.php
  modules/system/lang/fr/lang.php
  modules/system/lang/hu/lang.php
  modules/system/lang/id/lang.php
  modules/system/lang/it/lang.php
  modules/system/lang/ja/lang.php
  modules/system/lang/kr/lang.php
  modules/system/lang/lt/lang.php
  modules/system/lang/lv/lang.php
  modules/system/lang/nb-no/lang.php
  modules/system/lang/nl/lang.php
  modules/system/lang/pl/lang.php
  modules/system/lang/pt-br/lang.php
  modules/system/lang/pt-pt/lang.php
  modules/system/lang/ro/lang.php
  modules/system/lang/rs/lang.php
  modules/system/lang/ru/lang.php
  modules/system/lang/sk/lang.php
  modules/system/lang/sl/lang.php
  modules/system/lang/sv/lang.php
  modules/system/lang/th/lang.php
  modules/system/lang/tr/lang.php
  modules/system/lang/uk/lang.php
  modules/system/lang/vn/lang.php
  modules/system/lang/zh-cn/lang.php
  modules/system/lang/zh-tw/lang.php
  modules/system/models/MailSetting.php
  modules/system/models/mailsetting/_drivers_hint.htm
  modules/system/models/mailsetting/fields.yaml
Labels: Status: Completed, Type: Maintenance

#528 Add "send test message" button on MailSettings page
  modules/system/controllers/Settings.php
  modules/system/controllers/settings/update.htm
  modules/system/lang/en/lang.php
Labels: Type: Enhancement, Status: Review Needed

#529 Change send test message confirmation prompt.
  modules/system/controllers/settings/update.htm
  modules/system/lang/en/lang.php
Labels: Status: Completed, Type: Maintenance

#453 Update settings.json
  .vscode/settings.json
Labels: Status: Completed, Type: Maintenance

#537 Only show "Send test message" button on Mail Settings page
  modules/system/controllers/settings/update.htm
  modules/system/models/mailsetting/_send_test_button.htm
  modules/system/models/mailsetting/fields.yaml
Labels: Status: Completed, Type: Maintenance

#543 add spanish localization for 'auth.invalid_login'
  modules/backend/lang/es/lang.php
Labels: Status: Completed, Type: Maintenance

#539 Update MailLayout.php
  modules/system/models/MailLayout.php
Labels: Status: Completed, Type: Maintenance

#540 Update MailPartial.php
  modules/system/models/MailPartial.php
Labels: Status: Completed, Type: Maintenance
