Repository wintercms/winter, pull requests merged in 2022-02, with the labels that each got.

#434 Improved Latvian translation
  modules/backend/lang/lv/lang.php
Labels: Status: Completed, Type: Maintenance

#435 Update Backend/Japanease Language
  modules/backend/lang/ja/lang.php
Labels: Status: Completed, Type: Maintenance

#428 Added asset filter
  modules/system/twig/Extension.php
Labels: Status: Completed, Type: Enhancement

#446 Update japanese language files.
  modules/backend/lang/ja/lang.php
  modules/cms/lang/ja/lang.php
  modules/system/lang/ja/lang.php
Labels: Status: Completed, Type: Maintenance

#426 Add support for the Laravel asset() helpers
  config/app.php
  config/cache.php
Labels: Status: Completed, Type: Maintenance

#444 Add automatic package registration and improved installation to Laravel Mix support
  composer.json
  modules/system/ServiceProvider.php
  modules/system/assets/js/snowboard/build/snowboard.base.debug.js
  modules/system/assets/js/snowboard/build/snowboard.base.js
  modules/system/assets/js/snowboard/build/snowboard.extras.js
  modules/system/assets/js/snowboard/build/snowboard.request.js
  modules/system/assets/js/snowboard/winter.mix.js
  modules/system/classes/MixAssets.php
  modules/system/classes/PluginManager.php
  modules/system/console/MixCompile.php
  modules/system/console/MixInstall.php
  modules/system/console/MixList.php
  modules/system/console/MixWatch.php
  modules/system/console/fixtures/mix.webpack.js.fixture
  modules/system/console/fixtures/winter.mix.js.fixture
Labels: Status: Completed, Type: Enhancement

#456 Retain spaceless tag in Twig
  modules/system/twig/Extension.php
  modules/system/twig/SpacelessNode.php
  modules/system/twig/SpacelessTokenParser.php
  tests/unit/system/twig/SpacelessTest.php
Labels: Status: Completed, Type: Maintenance

#459 Add asset aliases for snowboard
  modules/system/classes/CombineAssets.php
Labels: Type: Maintenance

#457 fixes german translation of relation toolbar buttons
  modules/backend/lang/de/lang.php
Labels: Status: Completed, Type: Maintenance

#455 Refactor Twig registration and usage
  modules/cms/ServiceProvider.php
  modules/cms/classes/CmsCompoundObject.php
  modules/cms/classes/Controller.php
  modules/cms/twig/ComponentNode.php
  modules/cms/twig/ContentNode.php
  modules/cms/twig/DebugExtension.php
  modules/cms/twig/Extension.php
  modules/cms/twig/Loader.php
  modules/cms/twig/PageNode.php
  modules/cms/twig/PartialNode.php
  modules/cms/twig/ScriptsNode.php
  modules/cms/twig/StylesNode.php
  modules/system/ServiceProvider.php
  modules/system/classes/MailManager.php
  modules/system/classes/MarkupManager.php
  modules/system/traits/AssetMaker.php
  modules/system/twig/Engine.php
  modules/system/twig/Extension.php
  modules/system/twig/FilterTokenParser.php
  modules/system/twig/Loader.php
  modules/system/twig/SecurityPolicy.php
  modules/system/twig/SpacelessNode.php
  modules/system/twig/SpacelessTokenParser.php
  tests/unit/backend/models/ExportModelTest.php
  tests/unit/backend/widgets/FilterWidgetTest.php
  tests/unit/cms/classes/CmsObjectTest.php
  tests/unit/plugins/database/MorphManyModelTest.php
  tests/unit/system/twig/FilterTest.php
  tests/unit/system/twig/SpacelessTest.php
  themes/demo/partials/explain/ajax.htm
  themes/demo/partials/explain/plugins.htm
Labels: Status: Completed, Type: Maintenance

#463 Fix FormModelSaver for morphOne/hasOne relations
  modules/backend/traits/FormModelSaver.php
Labels: Status: Completed, Type: Maintenance

#464 Add asset alias for Snowboard extras css
  modules/system/classes/CombineAssets.php
Labels: Status: Completed, Type: Maintenance

#465 Fix route order with new system.beforeRoute and system.route events
  modules/backend/routes.php
  modules/cms/routes.php
  modules/system/routes.php
Labels: Status: Completed, Type: Maintenance

#471 Move scaffold commands
  modules/backend/ServiceProvider.php
  modules/backend/console/CreateController.php
  modules/backend/console/CreateFormWidget.php
  modules/backend/console/CreateReportWidget.php
  modules/backend/console/scaffold/controller/_list_toolbar.stub
  modules/backend/console/scaffold/controller/config_form.stub
  modules/backend/console/scaffold/controller/config_list.stub
  modules/backend/console/scaffold/controller/controller.stub
  modules/backend/console/scaffold/controller/create.stub
  modules/backend/console/scaffold/controller/index.stub
  modules/backend/console/scaffold/controller/preview.stub
  modules/backend/console/scaffold/controller/update.stub
  modules/backend/console/scaffold/formwidget/formwidget.stub
  modules/backend/console/scaffold/formwidget/javascript.stub
  modules/backend/console/scaffold/formwidget/partial.stub
  modules/backend/console/scaffold/formwidget/stylesheet.stub
  modules/backend/console/scaffold/reportwidget/reportwidget.stub
  modules/backend/console/scaffold/reportwidget/widget.stub
  modules/cms/ServiceProvider.php
  modules/cms/console/CreateComponent.php
  modules/cms/console/CreateTheme.php
  modules/cms/console/scaffold/component/component.stub
  modules/cms/console/scaffold/component/default.stub
  modules/cms/console/scaffold/theme/assets/js/app.stub
  modules/cms/console/scaffold/theme/assets/less/theme.stub
  modules/cms/console/scaffold/theme/layouts/default.stub
  modules/cms/console/scaffold/theme/pages/404.stub
  modules/cms/console/scaffold/theme/pages/error.stub
  modules/cms/console/scaffold/theme/pages/home.stub
  modules/cms/console/scaffold/theme/partials/meta/seo.stub
  modules/cms/console/scaffold/theme/partials/meta/styles.stub
  modules/cms/console/scaffold/theme/partials/site/footer.stub
  modules/cms/console/scaffold/theme/partials/site/header.stub
  modules/cms/console/scaffold/theme/theme.stub
  modules/cms/console/scaffold/theme/version.stub
  modules/system/ServiceProvider.php
  modules/system/aliases.php
  modules/system/console/CreateCommand.php
  modules/system/console/CreateModel.php
  modules/system/console/CreatePlugin.php
  modules/system/console/CreateSettings.php
  modules/system/console/scaffold/command/command.stub
  modules/system/console/scaffold/model/columns.stub
  modules/system/console/scaffold/model/create_table.stub
  modules/system/console/scaffold/model/fields.stub
  modules/system/console/scaffold/model/model.stub
  modules/system/console/scaffold/plugin/plugin.stub
  modules/system/console/scaffold/plugin/version.stub
  modules/system/console/scaffold/settings/fields.stub
  modules/system/console/scaffold/settings/model.stub
  modules/system/providers.php
Labels: Status: Completed, Type: Maintenance

#474 [FIX] Switched file to storage for plugin disabled
  modules/system/classes/PluginManager.php
Labels: Status: Completed, Type: Maintenance

#475 [FIX] Update manager mkdir on ro fs
  modules/system/classes/UpdateManager.php
Labels: Status: Completed, Type: Maintenance
