Repository wintercms/winter, pull requests merged in 2022-10, with the labels that each got.

#721 Remove default maxlength value from text fields
  modules/backend/widgets/form/partials/_field_text.php
Labels: Status: Completed, Type: Maintenance

#722 Fix export test
  modules/backend/models/ExportModel.php
  modules/backend/tests/models/ExportModelTest.php
Labels: Status: Completed, Type: Maintenance

#724 Adjust lookup for bootstrap in "winter:test"
  modules/system/console/WinterTest.php
Labels: Status: Completed, Type: Maintenance

#723 Add "Send password reset email" button to backend users update page
  modules/backend/controllers/Users.php
  modules/backend/controllers/users/_btn_password_reset.php
  modules/backend/lang/en/lang.php
  modules/backend/models/user/fields.yaml
Labels: Status: Completed, Type: Enhancement

#733 Add migrate to list of protected commands
  modules/system/ServiceProvider.php
Labels: Status: Completed, Type: Maintenance

#730 Update `failed_jobs` table to add missing `uuid` column.
  modules/system/database/migrations/2022_10_14_000027_Db_Jobs_FailedJobs_Update.php
Labels: Status: Completed, Type: Maintenance

#739 Set pivot data when initially syncing the relationship
  modules/backend/behaviors/RelationController.php
Labels: Status: Completed, Type: Maintenance

#732 Child Theme Improvements
  modules/cms/ServiceProvider.php
  modules/cms/classes/CodeParser.php
  modules/cms/classes/Controller.php
  modules/cms/classes/Theme.php
Labels: Type: Enhancement, Status: In Progress, hacktoberfest-acccepted

#742 Switch from using Request::getBasePath() to Url::asset()
  modules/cms/twig/FrameworkNode.php
Labels: Status: Completed, Type: Maintenance

#744 Fix bug when clicking move folder in media manager
  modules/backend/widgets/MediaManager.php
Labels: Status: Completed, Type: Maintenance
