Repository wintercms/winter, pull requests merged in 2022-08, with the labels that each got.

#632 Fix return types for MediaManager widget functions
  modules/backend/widgets/MediaManager.php
Labels: Status: Completed, Type: Maintenance

#631 Fix -c option in create:model command
  modules/system/console/CreateModel.php
Labels: Status: Completed, Type: Bug

#623 Update german translation
  modules/backend/lang/de/lang.php
  modules/cms/lang/de/lang.php
  modules/system/lang/de/client.php
  modules/system/lang/de/lang.php
  modules/system/lang/de/validation.php
Labels: Status: Completed, Type: Maintenance

#636 Improve Vietnamese Translation
  modules/backend/lang/vn/lang.php
Labels: Type: Maintenance

#633 Fix status widget output on clean installation
  modules/system/reportwidgets/Status.php
Labels: Status: Completed, Type: Maintenance

#611 Fix taglist default
  modules/backend/formwidgets/TagList.php
Labels: Status: Completed, Type: Maintenance

#644 Restore root phpunit configuration file
  phpunit.xml
Labels: Status: Completed, Type: Maintenance

#643 [POC] Disabled the plusplus checking rule
  modules/system/.eslintrc.json
Labels: Status: Completed, Type: Maintenance

#641 Style up migrations and updates using new Laravel CLI components
  modules/system/classes/UpdateManager.php
  modules/system/classes/VersionManager.php
Labels: Status: Completed, Type: Maintenance

#642 Add support for exit codes in MixCompile
  modules/system/console/MixCompile.php
  modules/system/console/fixtures/mix.webpack.js.fixture
  modules/system/tests/classes/PluginManagerTest.php
  modules/system/tests/console/MixCompileTest.php
  modules/system/tests/fixtures/npm/package-abc.json
  modules/system/tests/fixtures/npm/package-ac.json
  modules/system/tests/fixtures/plugins/mix/testa/Plugin.php
  modules/system/tests/fixtures/plugins/mix/testa/assets/.gitignore
  modules/system/tests/fixtures/plugins/mix/testa/assets/src/app.js
  modules/system/tests/fixtures/plugins/mix/testa/winter.mix.js
  modules/system/tests/fixtures/plugins/mix/testb/Plugin.php
  modules/system/tests/fixtures/plugins/mix/testb/assets/.gitignore
  modules/system/tests/fixtures/plugins/mix/testb/assets/src/app.js
  modules/system/tests/fixtures/plugins/mix/testb/winter.mix.js
  modules/system/tests/fixtures/plugins/mix/testc/Plugin.php
  modules/system/tests/fixtures/plugins/mix/testc/assets/.gitignore
  modules/system/tests/fixtures/plugins/mix/testc/assets/src/app.js
  modules/system/tests/fixtures/plugins/mix/testc/winter.mix.js
Labels: Status: Completed, Type: Maintenance

#639 Getting and storing system boot date value with Parameter model
  modules/system/database/migrations/2022_08_06_000026_Db_System_Add_App_Birthday_Date.php
  modules/system/reportwidgets/Status.php
Labels: Status: Completed, Type: Maintenance

#648 Fixed comment
  modules/system/console/MixCompile.php
Labels: Status: Completed, Type: Maintenance

#647 Added parent args to signature
  modules/system/console/MixWatch.php
Labels: Status: Completed, Type: Maintenance

#646 Fix typeo
  modules/system/console/MixWatch.php
Labels: Status: Completed, Type: Maintenance

#653 Make getOptionsFromModel() accessible on a form widget object
  modules/backend/widgets/Form.php
Labels: Status: Completed, Type: Maintenance

#650 Add support for data-request-parent
  modules/backend/formwidgets/FileUpload.php
  modules/backend/formwidgets/RecordFinder.php
  modules/backend/formwidgets/fileupload/assets/css/fileupload.css
  modules/backend/formwidgets/fileupload/assets/js/fileupload.js
  modules/backend/formwidgets/fileupload/assets/less/fileupload.base.less
  modules/backend/formwidgets/fileupload/partials/_config_form.php
  modules/backend/formwidgets/recordfinder/partials/_recordfinder.php
  modules/backend/formwidgets/recordfinder/partials/_recordfinder_form.php
  modules/system/assets/js/framework-min.js
  modules/system/assets/js/framework.combined-min.js
  modules/system/assets/js/framework.js
Labels: Status: Completed, Type: Enhancement

#656 Added support for extending upload systems to allow for streaming direct to S3
  config/filesystems.php
  modules/backend/formwidgets/FileUpload.php
  modules/backend/formwidgets/fileupload/assets/js/fileupload.js
  modules/backend/formwidgets/richeditor/assets/js/build-plugins-min.js
  modules/backend/formwidgets/richeditor/assets/js/richeditor.js
  modules/backend/traits/FormModelWidget.php
  modules/backend/traits/UploadableWidget.php
  modules/backend/widgets/MediaManager.php
  modules/backend/widgets/mediamanager/assets/js/mediamanager-browser-min.js
  modules/backend/widgets/mediamanager/assets/js/mediamanager.js
  modules/system/ServiceProvider.php
  modules/system/routes.php
Labels: Status: Completed, Type: Enhancement

#661 Properly align icon
  modules/system/assets/ui/less/form.less
Labels: Status: Completed, Type: Maintenance

#660 Properly center list-icon
  modules/backend/assets/less/controls/filelist.less
Labels: Status: Completed, Type: Maintenance

#665 feat: Make `winter:install` password generation transparent
  modules/backend/database/seeds/DatabaseSeeder.php
  modules/backend/database/seeds/SeedSetupAdmin.php
  modules/system/console/WinterInstall.php
Labels: Status: Completed, Type: Maintenance
