Repository wintercms/winter, pull requests merged in 2022-09, with the labels that each got.

#669 "0" value search fix
  modules/backend/widgets/Lists.php
Labels: Status: Completed, Type: Maintenance

#668 Add support for input range
  modules/backend/widgets/form/partials/_field_range.php
Labels: Status: Completed, Type: Enhancement

#624 Fix support for Winter Mix commands on Windows
  modules/system/classes/MixAssets.php
  modules/system/console/MixCompile.php
  modules/system/console/MixInstall.php
  modules/system/console/MixWatch.php
Labels: Status: Completed, Type: Maintenance

#673 Increase width of inputs
  modules/backend/widgets/mediamanager/partials/_crop-toolbar.php
Labels: Status: Completed, Type: Maintenance

#676 Fix issue where labels are not toggling the switches
  modules/backend/widgets/form/partials/_field_switch.php
Labels: Status: Completed, Type: Maintenance

#675 Fix richeditor html custom styles field comment translations
  modules/backend/lang/be/lang.php
  modules/backend/lang/ca/lang.php
  modules/backend/lang/cs/lang.php
  modules/backend/lang/da/lang.php
  modules/backend/lang/de/lang.php
  modules/backend/lang/el/lang.php
  modules/backend/lang/en/lang.php
  modules/backend/lang/es/lang.php
  modules/backend/lang/et/lang.php
  modules/backend/lang/fa/lang.php
  modules/backend/lang/fi/lang.php
  modules/backend/lang/fr/lang.php
  modules/backend/lang/hu/lang.php
  modules/backend/lang/it/lang.php
  modules/backend/lang/ja/lang.php
  modules/backend/lang/kr/lang.php
  modules/backend/lang/lt/lang.php
  modules/backend/lang/lv/lang.php
  modules/backend/lang/nb-no/lang.php
  modules/backend/lang/nl/lang.php
  modules/backend/lang/pl/lang.php
  modules/backend/lang/pt-br/lang.php
  modules/backend/lang/pt-pt/lang.php
  modules/backend/lang/ro/lang.php
  modules/backend/lang/rs/lang.php
  modules/backend/lang/ru/lang.php
  modules/backend/lang/sk/lang.php
  modules/backend/lang/sl/lang.php
  modules/backend/lang/th/lang.php
  modules/backend/lang/tr/lang.php
  modules/backend/lang/uk/lang.php
  modules/backend/lang/vn/lang.php
  modules/backend/lang/zh-cn/lang.php
  modules/backend/models/editorsetting/fields.yaml
Labels: Status: Completed, Type: Maintenance

#674 Add richeditor settings form french translation
  modules/backend/lang/fr/lang.php
Labels: Status: Completed, Type: Maintenance

#672 Clean up of base plugin test case class
  modules/system/tests/bootstrap/PluginTestCase.php
Labels: Status: Completed, Type: Maintenance

#681 Enforce elements beginning with # or . in accordance to the documentation
  modules/system/assets/js/build/system.js
  modules/system/assets/js/framework.js
  modules/system/assets/js/snowboard/ajax/Request.js
  modules/system/assets/js/snowboard/build/snowboard.base.debug.js
  modules/system/assets/js/snowboard/build/snowboard.base.js
  modules/system/assets/js/snowboard/build/snowboard.data-attr.js
  modules/system/assets/js/snowboard/build/snowboard.extras.js
  modules/system/assets/js/snowboard/build/snowboard.request.js
Labels: Status: Completed, Type: Maintenance

#682 Minor fix on numberrange filter
  modules/backend/widgets/filter/partials/_scope_numberrange.php
Labels: Status: Completed, Type: Maintenance

#685 Apply imageWidth/imageHeight to the image itself, not the whole widget.
  modules/backend/formwidgets/mediafinder/assets/js/mediafinder.js
Labels: Status: Completed, Type: Maintenance

#687 Harden Snowboard
  modules/system/.eslintrc.json
  modules/system/assets/js/build/system.js
  modules/system/assets/js/snowboard/build/snowboard.base.debug.js
  modules/system/assets/js/snowboard/build/snowboard.base.js
  modules/system/assets/js/snowboard/build/snowboard.extras.js
  modules/system/assets/js/snowboard/build/snowboard.request.js
  modules/system/assets/js/snowboard/main/InnerProxyHandler.js
  modules/system/assets/js/snowboard/main/PluginLoader.js
  modules/system/assets/js/snowboard/main/ProxyHandler.js
  modules/system/assets/js/snowboard/main/Snowboard.js
  modules/system/assets/js/snowboard/snowboard.base.debug.js
  modules/system/assets/js/snowboard/snowboard.base.js
  modules/system/tests/js/cases/snowboard/main/PluginLoader.test.js
  modules/system/tests/js/cases/snowboard/main/Snowboard.test.js
  modules/system/tests/js/fixtures/framework/TestPlugin.js
  modules/system/tests/js/fixtures/framework/TestSingleton.js
  modules/system/tests/js/fixtures/framework/TestSingletonWithDependency.js
Labels: Status: Completed, Type: Maintenance

#689 Correctly handle arrayed POST data in AJAX calls
  modules/backend/formwidgets/richeditor/assets/js/build-plugins-min.js
  modules/system/.eslintrc.json
  modules/system/assets/js/framework-min.js
  modules/system/assets/js/framework.combined-min.js
  modules/system/assets/js/framework.js
Labels: Status: Completed, Type: Maintenance

#694 fix plugin:remove argument name
  modules/system/console/WinterFresh.php
Labels: Status: Completed, Type: Maintenance

#701 Improved Ukrainian translation
  modules/system/lang/uk/lang.php
Labels: Status: Completed, Type: Maintenance

#700 Improved Russian translation
  modules/system/lang/ru/lang.php
Labels: Status: Completed, Type: Maintenance

#699 Fixing http (insecure transport) links to Winter CMS page
  modules/backend/behaviors/FormController.php
  modules/system/assets/js/framework.extras.js
  modules/system/assets/js/framework.js
  modules/system/assets/ui/docs/list.md
  modules/system/console/WinterUtil.php
  modules/system/controllers/updates/_project_form.php
  themes/demo/content/welcome.htm
  themes/demo/pages/plugins.htm
  themes/demo/theme.yaml
Labels: Status: Completed, Type: Maintenance

#698 Add "mix:run" command
  .github/workflows/tests.yml
  modules/system/.babelrc
  modules/system/ServiceProvider.php
  modules/system/console/MixRun.php
  modules/system/package.json
  modules/system/tests/js/.gitignore
  modules/system/tests/js/README.md
  modules/system/tests/js/package.json
Labels: Type: Enhancement, Status: Review Needed

#664 Add support for overriding phpunit bootstrap
  modules/system/console/WinterTest.php
Labels: Status: Completed, Type: Maintenance

#707 Fix column preview on Import
  modules/backend/behaviors/ImportExportController.php
Labels: Status: Completed, Type: Maintenance

#511 Fix "inline-options" class for checkbox list field
  modules/system/assets/ui/less/checkbox.less
Labels: Status: Completed, Type: Maintenance
