Repository wintercms/winter, pull requests merged in 2023-11, with the labels that each got.

#935 Populate migration file with actual model fields
  modules/system/console/CreateMigration.php
  modules/system/console/scaffold/migration/migration.create.stub
  modules/system/console/scaffold/migration/migration.update.stub
  modules/system/tests/console/CreateMigrationTest.php
  modules/system/tests/fixtures/plugins/winter/tester/models/TestModel.php
  modules/system/tests/fixtures/plugins/winter/tester/models/testmodel/fields.yaml
Labels: Type: Enhancement, Status: Review Needed

#1009 Add support for batched jobs
  config/queue.php
  modules/system/console/CreateJob.php
  modules/system/database/migrations/2023_10_20_000029_Db_Jobs_Batches.php
Labels: Type: Maintenance, Status: Testing Needed

#1011 Improved Russian translations
  modules/backend/lang/ru/lang.php
  modules/cms/lang/ru/lang.php
  modules/system/lang/ru/lang.php
  modules/system/lang/ru/validation.php
Labels: Status: Completed, Type: Maintenance

#824 Initial work on the create:test command
  modules/system/ServiceProvider.php
  modules/system/console/CreateJob.php
  modules/system/console/CreateTest.php
  modules/system/console/WinterTest.php
  modules/system/console/scaffold/command/command.stub
  modules/system/console/scaffold/job/job.queued.stub
  modules/system/console/scaffold/job/job.stub
  modules/system/console/scaffold/model/model.stub
  modules/system/console/scaffold/plugin/plugin.stub
  modules/system/console/scaffold/settings/model.stub
  modules/system/console/scaffold/test/pest.class.stub
  modules/system/console/scaffold/test/pest.init.stub
  modules/system/console/scaffold/test/pest.stub
  modules/system/console/scaffold/test/pest.unit.stub
  modules/system/console/scaffold/test/phpunit.stub
  modules/system/console/scaffold/test/test.class.stub
  modules/system/console/scaffold/test/test.plugin.stub
  modules/system/console/scaffold/test/test.stub
  modules/system/console/scaffold/test/test.unit.stub
Labels: Status: Completed, Type: Enhancement
