Repository wintercms/winter, pull requests merged in 2023-03, with the labels that each got.

#856 Fix typehint
  modules/cms/classes/Theme.php
Labels: Status: Completed, Type: Maintenance

#858 Fix Class "Cms\Classes\Log" not found error
  modules/cms/classes/Controller.php
Labels: Type: Maintenance, Status: Revision Needed

#861 Add 'themes.' prefix to let work backend theme localization again
  modules/cms/classes/Theme.php
Labels: Status: Completed, Type: Maintenance

#863 Manually register system class aliases in test bootstrap
  modules/system/tests/bootstrap/app.php
Labels: Status: Completed, Type: Maintenance

#867 Fixed JS error in IconPicker FormWidget
  modules/backend/formwidgets/iconpicker/assets/js/dist/iconpicker.js
  modules/backend/formwidgets/iconpicker/assets/js/src/iconpicker.js
  modules/backend/formwidgets/iconpicker/partials/_iconpicker.php
Labels: Status: Completed, Type: Maintenance

#710 Fix inspector depends functionality.
  modules/system/assets/ui/js/inspector.editor.dropdown.js
  modules/system/assets/ui/js/inspector.editor.objectlist.js
  modules/system/assets/ui/storm-min.js
Labels: Type: Maintenance, Status: Testing Needed

#875 [FIX] Multiple assets in combiner url
  modules/cms/classes/Controller.php
  modules/cms/tests/classes/ControllerTest.php
Labels: Status: Completed, Type: Maintenance

#874 Add support for pathSymbols in asset filenames
  modules/system/tests/traits/AssetMakerTest.php
  modules/system/traits/AssetMaker.php
Labels: Type: Maintenance, Status: Review Needed
