Repository wintercms/winter, pull requests merged in 2023-10, with the labels that each got.

#983 Hide toolbar when no content available
  modules/backend/widgets/toolbar/partials/_toolbar.php
Labels: Status: Completed, Type: Maintenance

#985 Fix fileupload thumbnail preview
  modules/backend/formwidgets/fileupload/assets/css/fileupload.css
  modules/backend/formwidgets/fileupload/assets/less/fileupload.imagemulti.less
Labels: Status: Completed, Type: Maintenance

#993 Fix issue when page has no components
  modules/cms/classes/CmsCompoundObject.php
Labels: Status: Completed, Type: Maintenance

#991 Further tweaks to the fileupload thumbnail styles
  modules/backend/formwidgets/fileupload/assets/css/fileupload.css
  modules/backend/formwidgets/fileupload/assets/less/fileupload.imagemulti.less
Labels: Status: Response Needed, Type: Maintenance

#987 Save / Restore initial list showTree config value
  modules/backend/widgets/Lists.php
Labels: Status: Completed, Type: Maintenance

#989 Fix install error for some paths
  modules/system/classes/FileManifest.php
  modules/system/tests/classes/FileManifestTest.php
Labels: Status: Completed, Type: Maintenance

#904 Added RelationManager FormWidget
  modules/backend/ServiceProvider.php
  modules/backend/formwidgets/RelationManager.php
  modules/backend/lang/en/lang.php
Labels: Status: Completed, Type: Enhancement

#998 Add `backend.list.extendColumnsBefore` event
  modules/backend/behaviors/ListController.php
  modules/backend/widgets/Lists.php
Labels: Status: Completed, Type: Enhancement
