Repository wintercms/winter, pull requests merged in 2023-02, with the labels that each got.

#836 Add support for extending head block on dashboard
  modules/backend/controllers/index/index.php
Labels: Status: Completed, Type: Maintenance

#841 Return correct URLs from File->getPublicPath for non-local disks
  modules/system/models/File.php
Labels: Status: Completed, Type: Maintenance

#847 Improved ru lang
  modules/backend/lang/ru/lang.php
  modules/cms/lang/ru/lang.php
Labels: Status: Response Needed, Type: Maintenance

#849 Improve French translations
  modules/backend/lang/fr/lang.php
  modules/system/lang/fr/client.php
  modules/system/lang/fr/lang.php
Labels: Type: Maintenance, Status: Accepted

#850 Include theme Blocks in the Tailwind theme scaffold
  modules/cms/console/scaffold/theme/tailwind/tailwind.config.stub
Labels: Status: Completed, Type: Enhancement
