Repository wintercms/winter, pull requests merged in 2024-04, with the labels that each got.

#974 Moved to Laravel 10
  .github/workflows/tests.yml
  .gitignore
  composer.json
  modules/backend/composer.json
  modules/backend/tests/classes/NavigationManagerTest.php
  modules/cms/composer.json
  modules/system/composer.json
  modules/system/console/WinterTest.php
  modules/system/tests/bootstrap/TestCase.php
Labels: Type: Maintenance, Status: Revision Needed

#1087 Add --no-progress and --json options to mix:compile and mix:list
  modules/system/console/MixCompile.php
  modules/system/console/MixList.php
  modules/system/console/fixtures/mix.webpack.js.fixture
Labels: Status: Completed, Type: Maintenance

#1095 Add showPageNumbers for relations
  modules/backend/behaviors/RelationController.php
Labels: Status: Completed, Type: Enhancement

#1101 Throw LoaderError when failing to find a Twig template
  modules/system/twig/Loader.php
Labels: Status: Completed, Type: Maintenance

#1096 Improve Font Awesome building and handling (update to 6.5.2)
  modules/backend/formwidgets/fileupload/assets/css/fileupload.css
  modules/backend/formwidgets/permissioneditor/assets/css/permissioneditor.css
  modules/backend/formwidgets/permissioneditor/assets/less/permissioneditor.less
  modules/system/ServiceProvider.php
  modules/system/assets/css/framework.extras.css
  modules/system/assets/css/snowboard.extras.css
  modules/system/assets/css/styles.css
  modules/system/assets/js/build/manifest.js
  modules/system/assets/js/build/system.debug.js
  modules/system/assets/js/build/system.js
  modules/system/assets/js/snowboard/build/snowboard.base.debug.js
  modules/system/assets/js/snowboard/build/snowboard.base.js
  modules/system/assets/js/snowboard/build/snowboard.data-attr.js
  modules/system/assets/js/snowboard/build/snowboard.extras.js
  modules/system/assets/js/snowboard/build/snowboard.request.js
  modules/system/assets/js/snowboard/build/snowboard.vendor.js
  modules/system/assets/less/framework.extras.less
  modules/system/assets/less/snowboard.extras.less
  modules/system/assets/ui/font/fa-brands-400.ttf
  modules/system/assets/ui/font/fa-brands-400.woff2
  modules/system/assets/ui/font/fa-regular-400.ttf
  modules/system/assets/ui/font/fa-regular-400.woff2
  modules/system/assets/ui/font/fa-solid-900.ttf
  modules/system/assets/ui/font/fa-solid-900.woff2
  modules/system/assets/ui/font/fa-v4compatibility.ttf
  modules/system/assets/ui/font/fa-v4compatibility.woff2
  modules/system/assets/ui/icons.css
  modules/system/assets/ui/less/global.variables.less
  modules/system/assets/ui/less/icon.icons.less
  modules/system/assets/ui/less/icon.less
  modules/system/assets/ui/less/icon.variables.less
  modules/system/assets/ui/storm.css
  modules/system/assets/ui/vendor/font-awesome-6/LICENSE.txt
  modules/system/assets/ui/vendor/font-awesome-6/_animated.less
  modules/system/assets/ui/vendor/font-awesome-6/_bordered-pulled.less
  modules/system/assets/ui/vendor/font-awesome-6/_core.less
  modules/system/assets/ui/vendor/font-awesome-6/_fixed-width.less
  modules/system/assets/ui/vendor/font-awesome-6/_icons.less
  modules/system/assets/ui/vendor/font-awesome-6/_list.less
  modules/system/assets/ui/vendor/font-awesome-6/_mixins.less
  modules/system/assets/ui/vendor/font-awesome-6/_rotated-flipped.less
  modules/system/assets/ui/vendor/font-awesome-6/_screen-reader.less
  modules/system/assets/ui/vendor/font-awesome-6/_shims.less
  modules/system/assets/ui/vendor/font-awesome-6/_sizing.less
  modules/system/assets/ui/vendor/font-awesome-6/_stacked.less
  modules/system/assets/ui/vendor/font-awesome-6/_variables.less
  modules/system/assets/ui/vendor/font-awesome-6/brands.less
  modules/system/assets/ui/vendor/font-awesome-6/fontawesome.less
  modules/system/assets/ui/vendor/font-awesome-6/regular.less
  modules/system/assets/ui/vendor/font-awesome-6/solid.less
  modules/system/assets/ui/vendor/font-awesome-6/v4-shims.less
  modules/system/package.json
  modules/system/winter.mix.js
Labels: Status: Completed, Type: Maintenance

#1084 Remove encryption setting on backend mail settings page & config
  config/mail.php
  modules/system/lang/be/lang.php
  modules/system/lang/bg/lang.php
  modules/system/lang/ca/lang.php
  modules/system/lang/cs/lang.php
  modules/system/lang/da/lang.php
  modules/system/lang/de/lang.php
  modules/system/lang/el/lang.php
  modules/system/lang/en/lang.php
  modules/system/lang/es-ar/lang.php
  modules/system/lang/es/lang.php
  modules/system/lang/et/lang.php
  modules/system/lang/fa/lang.php
  modules/system/lang/fi/lang.php
  modules/system/lang/fr/lang.php
  modules/system/lang/hu/lang.php
  modules/system/lang/id/lang.php
  modules/system/lang/it/lang.php
  modules/system/lang/ja/lang.php
  modules/system/lang/kr/lang.php
  modules/system/lang/lt/lang.php
  modules/system/lang/lv/lang.php
  modules/system/lang/nb-no/lang.php
  modules/system/lang/nl/lang.php
  modules/system/lang/pl/lang.php
  modules/system/lang/pt-br/lang.php
  modules/system/lang/pt-pt/lang.php
  modules/system/lang/ro/lang.php
  modules/system/lang/rs/lang.php
  modules/system/lang/ru/lang.php
  modules/system/lang/sk/lang.php
  modules/system/lang/sl/lang.php
  modules/system/lang/sv/lang.php
  modules/system/lang/th/lang.php
  modules/system/lang/tr/lang.php
  modules/system/lang/uk/lang.php
  modules/system/lang/vn/lang.php
  modules/system/lang/zh-cn/lang.php
  modules/system/lang/zh-tw/lang.php
  modules/system/models/MailSetting.php
  modules/system/models/mailsetting/fields.yaml
Labels: Type: Maintenance, Status: Review Needed

#1099 Do not ignore hidden/disabled fields in onRefresh
  modules/backend/widgets/Form.php
Labels: Status: Completed, Type: Maintenance

#755 Show checkboxlist options when in preview / disabled
  modules/backend/widgets/form/partials/_field_checkboxlist.php
Labels: Status: Response Needed, Type: Maintenance

#1112 Restore showPageNumber default to true in the RelationController Lists widget
  modules/backend/behaviors/RelationController.php
Labels: Status: Completed, Type: Maintenance

#1114 Improved Latvian translation
  modules/backend/lang/lv/lang.php
  modules/system/lang/lv/lang.php
Labels: Status: Completed, Type: Maintenance
