Repository wintercms/winter, pull requests merged in 2024-10, with the labels that each got.

#1216 Create Devcontainer build
  .devcontainer/.vscode/launch.json
  .devcontainer/Dockerfile
  .devcontainer/README.md
  .devcontainer/devcontainer.json
  .devcontainer/local-features/apache-config/devcontainer-feature.json
  .devcontainer/local-features/apache-config/install.sh
  .devcontainer/local-features/bootstrap-winter/bootstrap.sh
  .devcontainer/local-features/bootstrap-winter/codespaces.php
  .devcontainer/local-features/bootstrap-winter/devcontainer-feature.json
  .devcontainer/local-features/bootstrap-winter/install.sh
  .devcontainer/local-features/bootstrap-winter/update-composer.php
  .gitattributes
  .gitignore
Labels: Type: Conceptual Enhancement, Status: Review Needed

#1209 Add create:factory command
  modules/system/ServiceProvider.php
  modules/system/console/CreateFactory.php
  modules/system/console/CreateModel.php
  modules/system/console/scaffold/factory/factory.stub
Labels: Status: Completed, Type: Enhancement

#1218 Make the whole repeater-item clickable for expansion
  modules/backend/formwidgets/repeater/assets/js/repeater.js
Labels: Status: Completed, Type: Enhancement

#1220 Revert "Make the whole repeater-item clickable for expansion (#1218)"
  modules/backend/formwidgets/repeater/assets/js/repeater.js
Labels: Priority: High, Type: Maintenance

#1221 Expand repeater items by clicking on their title
  modules/backend/formwidgets/repeater/assets/js/repeater.js
Labels: Status: Completed, Type: Maintenance

#1229 Make entire fileupload field clickable in single file mode
  modules/backend/formwidgets/fileupload/assets/css/fileupload.css
  modules/backend/formwidgets/fileupload/assets/js/fileupload.js
  modules/backend/formwidgets/fileupload/assets/less/fileupload.filesingle.less
Labels: Status: Completed, Type: Enhancement

#1228 Allow dynamic methods to be used for custom list column types
  modules/backend/widgets/Lists.php
Labels: Status: Completed, Type: Maintenance

#1231 Fix minor box shadow issue with recordfinder clear button
  modules/backend/formwidgets/recordfinder/partials/_recordfinder.php
Labels: maintenance

#1202 Completed npm commands (npm:install, npm:update, npm:run)
  modules/system/.eslintignore
  modules/system/ServiceProvider.php
  modules/system/classes/asset/PackageJson.php
  modules/system/classes/asset/PackageManager.php
  modules/system/console/asset/AssetInstall.php
  modules/system/console/asset/NpmRun.php
  modules/system/console/asset/NpmUpdate.php
  modules/system/console/asset/mix/MixInstall.php
  modules/system/console/asset/npm/NpmCommand.php
  modules/system/console/asset/npm/NpmInstall.php
  modules/system/console/asset/npm/NpmRun.php
  modules/system/console/asset/npm/NpmUpdate.php
  modules/system/console/asset/vite/ViteInstall.php
  modules/system/tests/classes/asset/PackageJsonTest.php
  modules/system/tests/console/asset/NpmTestTrait.php
  modules/system/tests/console/asset/mix/MixCompileTest.php
  modules/system/tests/console/asset/mix/MixCreateTest.php
  modules/system/tests/console/asset/mix/MixInstallTest.php
  modules/system/tests/console/asset/npm/NpmInstallTest.php
  modules/system/tests/console/asset/npm/NpmRunTest.php
  modules/system/tests/console/asset/npm/NpmUpdateTest.php
  modules/system/tests/console/asset/vite/ViteCompileTest.php
  modules/system/tests/console/asset/vite/ViteCreateTest.php
  modules/system/tests/console/asset/vite/ViteInstallTest.php
  modules/system/tests/fixtures/npm/package-corrupt.json
  modules/system/tests/fixtures/npm/package-vitetheme.json
  modules/system/tests/fixtures/themes/assettest/assets/css/theme.css
  modules/system/tests/fixtures/themes/assettest/assets/javascript/theme.js
  modules/system/tests/fixtures/themes/assettest/vite.config.mjs
  modules/system/tests/fixtures/themes/assettest/winter.mix.js
  modules/system/tests/fixtures/themes/npmtest/package.json
  modules/system/tests/fixtures/themes/npmtest/vite.config.mjs
  modules/system/tests/fixtures/themes/npmtest/winter.mix.js
  modules/system/tests/package-testing.json
Labels: enhancement

#1239 Add routePersistence parameter to Page::resolveMenuItem()
  modules/cms/classes/Page.php
Labels: maintenance

#1235 Attach original AJAX framework events to Snowboard in Backend
  modules/backend/assets/css/winter.css
  modules/backend/assets/ui/js/ajax/Handler.js
  modules/backend/assets/ui/js/build/backend.js
  modules/backend/formwidgets/codeeditor/assets/js/build-min.js
  modules/backend/formwidgets/fileupload/assets/css/fileupload.css
  modules/backend/widgets/mediamanager/assets/js/mediamanager-browser-min.js
  modules/system/assets/js/build/system.debug.js
  modules/system/assets/js/build/system.js
  modules/system/assets/js/framework.combined-min.js
  modules/system/assets/js/lang/lang.tr.js
  modules/system/assets/js/snowboard/build/snowboard.data-attr.js
  modules/system/assets/js/snowboard/build/snowboard.extras.js
  modules/system/assets/js/snowboard/extras/AttachLoading.js
Labels: maintenance, needs review
