Repository wintercms/winter, pull requests merged in 2024-07, with the labels that each got.

#1154 Improves drag and drop sorting of tree views
  modules/backend/assets/css/winter.css
  modules/backend/assets/less/controls/treeview.less
Labels: Status: Completed, Type: Enhancement

#1155 Disable autocomplete on password and sensitive fields by default
  modules/backend/formwidgets/sensitive/partials/_sensitive.php
  modules/backend/widgets/form/partials/_field_password.php
Labels: Status: Completed, Type: Maintenance

#1157 Fix issues with components with latest Foundation\Application changes
  modules/cms/classes/ComponentManager.php
  modules/cms/widgets/ComponentList.php
Labels: Type: Maintenance, Status: Review Needed

#1022 Add asset priority & use AssetMaker for global backend assets
  modules/backend/classes/Controller.php
  modules/backend/layouts/_head.php
  modules/backend/layouts/auth.php
  modules/system/tests/traits/AssetMakerTest.php
  modules/system/traits/AssetMaker.php
Labels: Type: Maintenance, Status: Review Needed

#1141 Integrate Vite & Rework Mix
  .gitattributes
  modules/cms/twig/Extension.php
  modules/cms/twig/ScriptsNode.php
  modules/system/.eslintignore
  modules/system/ServiceProvider.php
  modules/system/classes/CompilableAssets.php
  modules/system/classes/MixAssets.php
  modules/system/classes/PackageJson.php
  modules/system/classes/Vite.php
  modules/system/console/MixCompile.php
  modules/system/console/MixWatch.php
  modules/system/console/NpmRun.php
  modules/system/console/NpmUpdate.php
  modules/system/console/asset/AssetCompile.php
  modules/system/console/asset/AssetConfig.php
  modules/system/console/asset/AssetInstall.php
  modules/system/console/asset/AssetList.php
  modules/system/console/asset/fixtures/config/css/default.css.fixture
  modules/system/console/asset/fixtures/config/css/tailwind.css.fixture
  modules/system/console/asset/fixtures/config/js/default.js.fixture
  modules/system/console/asset/fixtures/config/js/vue.js.fixture
  modules/system/console/asset/fixtures/config/mix/winter.mix.js.fixture
  modules/system/console/asset/fixtures/config/mix/winter.mix.tailwind.js.fixture
  modules/system/console/asset/fixtures/config/mix/winter.mix.tailwind.vue.js.fixture
  modules/system/console/asset/fixtures/config/mix/winter.mix.vue.js.fixture
  modules/system/console/asset/fixtures/config/tailwind/postcss.config.js.fixture
  modules/system/console/asset/fixtures/config/tailwind/tailwind.plugin.config.js.fixture
  modules/system/console/asset/fixtures/config/tailwind/tailwind.theme.config.js.fixture
  modules/system/console/asset/fixtures/config/vite/vite.config.js.fixture
  modules/system/console/asset/fixtures/config/vite/vite.config.tailwind.js.fixture
  modules/system/console/asset/fixtures/config/vite/vite.config.tailwind.vue.js.fixture
  modules/system/console/asset/fixtures/config/vite/vite.config.vue.js.fixture
  modules/system/console/asset/fixtures/mix.webpack.js.fixture
  modules/system/console/asset/fixtures/winter.mix.js.fixture
  modules/system/console/asset/mix/MixCompile.php
  modules/system/console/asset/mix/MixConfig.php
  modules/system/console/asset/mix/MixInstall.php
  modules/system/console/asset/mix/MixList.php
  modules/system/console/asset/mix/MixWatch.php
  modules/system/console/asset/vite/ViteCompile.php
  modules/system/console/asset/vite/ViteConfig.php
  modules/system/console/asset/vite/ViteInstall.php
  modules/system/console/asset/vite/ViteList.php
  modules/system/console/asset/vite/ViteWatch.php
  modules/system/tests/classes/PackageJsonTest.php
  modules/system/tests/console/MixCompileTest.php
  modules/system/tests/console/MixConfigTest.php
  modules/system/tests/console/ViteCompileTest.php
  modules/system/tests/console/ViteConfigTest.php
  modules/system/tests/console/WinterEnvTest.php
  modules/system/tests/fixtures/npm/package-test.json
  modules/system/tests/fixtures/npm/package-vitetheme.json
  modules/system/tests/fixtures/themes/vitetest/assets/css/theme.css
  modules/system/tests/fixtures/themes/vitetest/assets/javascript/theme.js
  modules/system/tests/fixtures/themes/vitetest/vite.config.mjs
  modules/system/traits/AssetMaker.php
Labels: Status: Completed, Type: Enhancement

#1167 Added support for enabling mix manifest
  modules/system/console/asset/fixtures/mix.webpack.js.fixture
Labels: Status: Completed, Type: Maintenance

#1166 Allow for File model IDs to be UUIDs
  modules/backend/formwidgets/fileupload/partials/_file_multi.php
  modules/backend/formwidgets/fileupload/partials/_file_single.php
  modules/backend/formwidgets/fileupload/partials/_image_multi.php
  modules/backend/formwidgets/fileupload/partials/_image_single.php
Labels: Status: Completed, Type: Maintenance

#1164 Add asset BundleManager & re-organize the asset helper classes
  modules/system/ServiceProvider.php
  modules/system/classes/MailManager.php
  modules/system/classes/asset/BundleManager.php
  modules/system/classes/asset/PackageJson.php
  modules/system/classes/asset/PackageManager.php
  modules/system/classes/asset/Vite.php
  modules/system/console/asset/AssetCompile.php
  modules/system/console/asset/AssetConfig.php
  modules/system/console/asset/AssetCreate.php
  modules/system/console/asset/AssetInstall.php
  modules/system/console/asset/AssetList.php
  modules/system/console/asset/NpmRun.php
  modules/system/console/asset/NpmUpdate.php
  modules/system/console/asset/fixtures/config/mix/winter.mix.tailwind.js.fixture
  modules/system/console/asset/fixtures/config/mix/winter.mix.tailwind.vue.js.fixture
  modules/system/console/asset/fixtures/config/mix/winter.mix.vue.js.fixture
  modules/system/console/asset/fixtures/config/vite/vite.config.mjs.fixture
  modules/system/console/asset/fixtures/config/vite/vite.config.tailwind.js.fixture
  modules/system/console/asset/fixtures/config/vite/vite.config.tailwind.vue.js.fixture
  modules/system/console/asset/fixtures/config/vite/vite.config.vue.js.fixture
  modules/system/console/asset/mix/MixCreate.php
  modules/system/console/asset/mix/MixInstall.php
  modules/system/console/asset/mix/MixWatch.php
  modules/system/console/asset/vite/ViteConfig.php
  modules/system/console/asset/vite/ViteCreate.php
  modules/system/console/asset/vite/ViteInstall.php
  modules/system/tests/classes/asset/BundleManagerTest.php
  modules/system/tests/classes/asset/PackageJsonTest.php
  modules/system/tests/console/asset/MixCompileTest.php
  modules/system/tests/console/asset/MixCreateTest.php
  modules/system/tests/console/asset/ViteCompileTest.php
  modules/system/tests/console/asset/ViteCreateTest.php
Labels: Status: Completed, Type: Maintenance

#1169 Added fix for namespace change
  modules/cms/twig/Extension.php
  modules/system/traits/AssetMaker.php
Labels: Status: Completed, Type: Maintenance

#1175 Fix Mix webpack config not being cleaned
  modules/system/console/asset/mix/MixCompile.php
  modules/system/console/asset/mix/MixWatch.php
Labels: Status: Completed, Type: Maintenance
