Repository wintercms/winter, pull requests merged in 2024-11, with the labels that each got.

#1249 Remove redundent vite logic
  modules/system/console/asset/vite/ViteWatch.php
Labels: accepted

#1126 Revert applyFiltersFromModel change
  modules/backend/widgets/Form.php
Labels: maintenance

#1226 Support --isolatable flag on migration command
  modules/system/console/WinterUp.php
Labels: maintenance

#1191 Fix displaying repeater item titles in preview contexts
  modules/backend/formwidgets/repeater/assets/js/repeater.js
Labels: maintenance

#1253 Vite theme create
  modules/cms/console/CreateTheme.php
  modules/cms/console/scaffold/theme/tailwind/package.stub
  modules/cms/console/scaffold/theme/tailwind/partials/meta/styles.stub
  modules/cms/console/scaffold/theme/tailwind/partials/site/footer.stub
  modules/cms/console/scaffold/theme/tailwind/tailwind.config.stub
  modules/cms/console/scaffold/theme/tailwind/winter.mix.stub
  modules/system/console/asset/AssetCompile.php
  modules/system/console/asset/AssetCreate.php
  modules/system/console/asset/AssetInstall.php
  modules/system/console/asset/fixtures/config/tailwind/postcss.config.js.fixture
  modules/system/console/asset/mix/MixCompile.php
  modules/system/console/asset/mix/MixCreate.php
  modules/system/console/asset/mix/MixInstall.php
  modules/system/console/asset/mix/MixWatch.php
  modules/system/console/asset/vite/ViteCompile.php
  modules/system/console/asset/vite/ViteCreate.php
  modules/system/console/asset/vite/ViteInstall.php
  modules/system/console/asset/vite/ViteWatch.php
Labels: enhancement

#1257 Move after login logic to event listener instead of controller
  modules/backend/ServiceProvider.php
  modules/backend/controllers/Auth.php
  modules/backend/models/User.php
Labels: maintenance
