Repository wintercms/winter, pull requests merged in 2024-09, with the labels that each got.

#1208 Add --sidebar option to create:controller
  modules/backend/console/CreateController.php
  modules/backend/console/scaffold/controller/controller.stub
  modules/backend/console/scaffold/controller/sidebar/create.stub
  modules/backend/console/scaffold/controller/sidebar/preview.stub
  modules/backend/console/scaffold/controller/sidebar/update.stub
  modules/backend/console/scaffold/controller/standard/create.stub
  modules/backend/console/scaffold/controller/standard/preview.stub
  modules/backend/console/scaffold/controller/standard/update.stub
Labels: Type: Enhancement, Status: Review Needed

#1204 Fix job class generated twice when using the sync option
  modules/system/console/CreateJob.php
Labels: Status: Completed, Type: Maintenance

#1207 Allow command names to contain number
  modules/system/console/CreateCommand.php
  modules/system/tests/console/CreateCommandTest.php
Labels: Status: Completed, Type: Maintenance

#1215 Add --batchable option to create:job command
  modules/system/console/CreateJob.php
  modules/system/console/scaffold/job/job.batched.stub
Labels: Status: Completed, Type: Enhancement

#1210 Improved French translation
  modules/backend/lang/fr/lang.php
Labels: Status: Completed, Type: Maintenance

#1201 Make stripe loader configurable with data attribute
  modules/system/assets/js/snowboard/ajax/handlers/AttributeRequest.js
Labels: Status: Completed, Type: Enhancement

#1192 Add support for translation strings in FormField->options()
  modules/backend/classes/FormField.php
Labels: Status: Completed, Type: Maintenance
