Repository wintercms/winter, pull requests merged in 2025-01, with the labels that each got.

#1276 Remove empty item for all taglist modes
  modules/backend/formwidgets/TagList.php
  modules/backend/formwidgets/taglist/partials/_taglist.php
Labels: maintenance

#1296 Make entire mediafinder field clickable when mode=file
  modules/backend/formwidgets/mediafinder/assets/js/mediafinder.js
Labels: enhancement

#1294 Fix TagList returning an object in array mode
  modules/backend/formwidgets/TagList.php
Labels: maintenance, accepted

#1295 Only make recordfinder clickable if not disabled
  modules/backend/formwidgets/recordfinder/partials/_recordfinder.php
Labels: needs response

#1301 Allow users to zoom the backend on mobile
  modules/backend/layouts/_head.php
Labels: enhancement

#1300 Repeater: Always send a value in the Form data
  modules/backend/formwidgets/Repeater.php
  modules/backend/formwidgets/repeater/partials/_repeater.php
Labels: maintenance
