Repository wintercms/winter, pull requests merged in 2025-07, with the labels that each got.

#1387 Fixes winter:util purge uploads deleting files that are in-use
  modules/system/console/WinterUtil.php
Labels: maintenance, accepted

#1388 Vite Base Rework
  modules/system/console/asset/AssetCompile.php
  modules/system/console/asset/fixtures/config/vite/vite.config.mjs.fixture
  modules/system/console/asset/vite/ViteCompile.php
Labels: maintenance

#1314 Allow "winter:util compile" command to download Font Awesome if required
  modules/system/console/WinterUtil.php
Labels: maintenance

#1315 Add failover transport to MailSetting
  modules/system/lang/en/lang.php
  modules/system/models/MailSetting.php
  modules/system/models/mailsetting/fields.yaml
Labels: enhancement
