Repository wintercms/winter, pull requests merged in 2025-02, with the labels that each got.

#1293 Add allowList functionality to Twig security policy
  modules/cms/classes/Controller.php
  modules/system/tests/twig/SecurityPolicyTest.php
  modules/system/twig/SecurityPolicy.php
Labels: maintenance

#1272 Support customizing the Vite build directory
  modules/cms/twig/Extension.php
  modules/system/classes/asset/Vite.php
Labels: maintenance, needs review

#1303 Added better log viewing
  modules/cms/classes/CodeParser.php
  modules/system/assets/js/eventlogs/exception-beautifier.links.js
  modules/system/controllers/eventlogs/_field_details.php
  modules/system/controllers/eventlogs/preview.php
  modules/system/models/eventlog/fields.yaml
Labels: enhancement

#1304 Add support for React
  modules/cms/twig/Extension.php
  modules/system/assets/js/lang/lang.tr.js
  modules/system/classes/asset/BundleManager.php
  modules/system/classes/asset/Vite.php
  modules/system/console/asset/AssetCreate.php
  modules/system/console/asset/fixtures/config/react/App.jsx.fixture
  modules/system/console/asset/fixtures/config/react/package.js.fixture
  modules/system/console/asset/fixtures/config/react/package.jsx.fixture
  modules/system/console/asset/fixtures/config/tailwind/tailwind.plugin.config.js.fixture
  modules/system/console/asset/fixtures/config/tailwind/tailwind.theme.config.js.fixture
  modules/system/console/asset/fixtures/config/vite/vite.config.mjs.fixture
  modules/system/console/asset/vite/ViteCreate.php
  modules/system/tests/console/asset/mix/MixCreateTest.php
  modules/system/tests/console/asset/vite/ViteCreateTest.php
Labels: enhancement

#1309 Added fix for some labels in the new exception page
  modules/system/controllers/eventlogs/_field_details.php
Labels: maintenance

#1318 Add fix for colorpicker hex with alpha saving
  modules/backend/formwidgets/ColorPicker.php
Labels: maintenance

#1319 Migrate logging code to winter from storm to prevent excess file logs being written
  modules/system/ServiceProvider.php
  modules/system/models/EventLog.php
Labels: maintenance

#1306 Add support for PHP 8.4
  .github/workflows/tests.yml
Labels: maintenance

#1320 Add fix for maintenance setting containing value but null ip list
  modules/cms/models/MaintenanceSetting.php
Labels: maintenance
